// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: paxos.proto

#include "paxos.pb.h"
#include "paxos.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace paxos {

static const char* ClientService_method_names[] = {
  "/paxos.ClientService/SubmitTransaction",
  "/paxos.ClientService/SendClientReply",
};

std::unique_ptr< ClientService::Stub> ClientService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ClientService::Stub> stub(new ClientService::Stub(channel, options));
  return stub;
}

ClientService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SubmitTransaction_(ClientService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendClientReply_(ClientService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ClientService::Stub::SubmitTransaction(::grpc::ClientContext* context, const ::paxos::ClientRequest& request, ::paxos::TransactionAck* response) {
  return ::grpc::internal::BlockingUnaryCall< ::paxos::ClientRequest, ::paxos::TransactionAck, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SubmitTransaction_, context, request, response);
}

void ClientService::Stub::async::SubmitTransaction(::grpc::ClientContext* context, const ::paxos::ClientRequest* request, ::paxos::TransactionAck* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::paxos::ClientRequest, ::paxos::TransactionAck, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SubmitTransaction_, context, request, response, std::move(f));
}

void ClientService::Stub::async::SubmitTransaction(::grpc::ClientContext* context, const ::paxos::ClientRequest* request, ::paxos::TransactionAck* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SubmitTransaction_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::paxos::TransactionAck>* ClientService::Stub::PrepareAsyncSubmitTransactionRaw(::grpc::ClientContext* context, const ::paxos::ClientRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::paxos::TransactionAck, ::paxos::ClientRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SubmitTransaction_, context, request);
}

::grpc::ClientAsyncResponseReader< ::paxos::TransactionAck>* ClientService::Stub::AsyncSubmitTransactionRaw(::grpc::ClientContext* context, const ::paxos::ClientRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSubmitTransactionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ClientService::Stub::SendClientReply(::grpc::ClientContext* context, const ::paxos::ClientReply& request, ::paxos::TransactionAck* response) {
  return ::grpc::internal::BlockingUnaryCall< ::paxos::ClientReply, ::paxos::TransactionAck, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendClientReply_, context, request, response);
}

void ClientService::Stub::async::SendClientReply(::grpc::ClientContext* context, const ::paxos::ClientReply* request, ::paxos::TransactionAck* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::paxos::ClientReply, ::paxos::TransactionAck, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendClientReply_, context, request, response, std::move(f));
}

void ClientService::Stub::async::SendClientReply(::grpc::ClientContext* context, const ::paxos::ClientReply* request, ::paxos::TransactionAck* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendClientReply_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::paxos::TransactionAck>* ClientService::Stub::PrepareAsyncSendClientReplyRaw(::grpc::ClientContext* context, const ::paxos::ClientReply& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::paxos::TransactionAck, ::paxos::ClientReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendClientReply_, context, request);
}

::grpc::ClientAsyncResponseReader< ::paxos::TransactionAck>* ClientService::Stub::AsyncSendClientReplyRaw(::grpc::ClientContext* context, const ::paxos::ClientReply& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendClientReplyRaw(context, request, cq);
  result->StartCall();
  return result;
}

ClientService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ClientService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ClientService::Service, ::paxos::ClientRequest, ::paxos::TransactionAck, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ClientService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::paxos::ClientRequest* req,
             ::paxos::TransactionAck* resp) {
               return service->SubmitTransaction(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ClientService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ClientService::Service, ::paxos::ClientReply, ::paxos::TransactionAck, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ClientService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::paxos::ClientReply* req,
             ::paxos::TransactionAck* resp) {
               return service->SendClientReply(ctx, req, resp);
             }, this)));
}

ClientService::Service::~Service() {
}

::grpc::Status ClientService::Service::SubmitTransaction(::grpc::ServerContext* context, const ::paxos::ClientRequest* request, ::paxos::TransactionAck* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ClientService::Service::SendClientReply(::grpc::ServerContext* context, const ::paxos::ClientReply* request, ::paxos::TransactionAck* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* Paxos_method_names[] = {
  "/paxos.Paxos/Prepare",
  "/paxos.Paxos/Accept",
  "/paxos.Paxos/Commit",
  "/paxos.Paxos/SendClientRequest",
  "/paxos.Paxos/NewView",
  "/paxos.Paxos/ReceiveAcceptAck",
  "/paxos.Paxos/SendAliveUpdate",
  "/paxos.Paxos/GetNodeInfo",
  "/paxos.Paxos/SendMoveOn",
  "/paxos.Paxos/SendTwoPCMsg",
};

std::unique_ptr< Paxos::Stub> Paxos::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Paxos::Stub> stub(new Paxos::Stub(channel, options));
  return stub;
}

Paxos::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Prepare_(Paxos_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Accept_(Paxos_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Commit_(Paxos_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendClientRequest_(Paxos_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_NewView_(Paxos_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReceiveAcceptAck_(Paxos_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendAliveUpdate_(Paxos_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetNodeInfo_(Paxos_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendMoveOn_(Paxos_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendTwoPCMsg_(Paxos_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Paxos::Stub::Prepare(::grpc::ClientContext* context, const ::paxos::PrepareRequest& request, ::paxos::PromiseResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::paxos::PrepareRequest, ::paxos::PromiseResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Prepare_, context, request, response);
}

void Paxos::Stub::async::Prepare(::grpc::ClientContext* context, const ::paxos::PrepareRequest* request, ::paxos::PromiseResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::paxos::PrepareRequest, ::paxos::PromiseResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Prepare_, context, request, response, std::move(f));
}

void Paxos::Stub::async::Prepare(::grpc::ClientContext* context, const ::paxos::PrepareRequest* request, ::paxos::PromiseResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Prepare_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::paxos::PromiseResponse>* Paxos::Stub::PrepareAsyncPrepareRaw(::grpc::ClientContext* context, const ::paxos::PrepareRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::paxos::PromiseResponse, ::paxos::PrepareRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Prepare_, context, request);
}

::grpc::ClientAsyncResponseReader< ::paxos::PromiseResponse>* Paxos::Stub::AsyncPrepareRaw(::grpc::ClientContext* context, const ::paxos::PrepareRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPrepareRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Paxos::Stub::Accept(::grpc::ClientContext* context, const ::paxos::AcceptedEntry& request, ::paxos::Ack* response) {
  return ::grpc::internal::BlockingUnaryCall< ::paxos::AcceptedEntry, ::paxos::Ack, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Accept_, context, request, response);
}

void Paxos::Stub::async::Accept(::grpc::ClientContext* context, const ::paxos::AcceptedEntry* request, ::paxos::Ack* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::paxos::AcceptedEntry, ::paxos::Ack, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Accept_, context, request, response, std::move(f));
}

void Paxos::Stub::async::Accept(::grpc::ClientContext* context, const ::paxos::AcceptedEntry* request, ::paxos::Ack* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Accept_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::paxos::Ack>* Paxos::Stub::PrepareAsyncAcceptRaw(::grpc::ClientContext* context, const ::paxos::AcceptedEntry& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::paxos::Ack, ::paxos::AcceptedEntry, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Accept_, context, request);
}

::grpc::ClientAsyncResponseReader< ::paxos::Ack>* Paxos::Stub::AsyncAcceptRaw(::grpc::ClientContext* context, const ::paxos::AcceptedEntry& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAcceptRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Paxos::Stub::Commit(::grpc::ClientContext* context, const ::paxos::CommitEntry& request, ::paxos::Ack* response) {
  return ::grpc::internal::BlockingUnaryCall< ::paxos::CommitEntry, ::paxos::Ack, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Commit_, context, request, response);
}

void Paxos::Stub::async::Commit(::grpc::ClientContext* context, const ::paxos::CommitEntry* request, ::paxos::Ack* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::paxos::CommitEntry, ::paxos::Ack, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Commit_, context, request, response, std::move(f));
}

void Paxos::Stub::async::Commit(::grpc::ClientContext* context, const ::paxos::CommitEntry* request, ::paxos::Ack* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Commit_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::paxos::Ack>* Paxos::Stub::PrepareAsyncCommitRaw(::grpc::ClientContext* context, const ::paxos::CommitEntry& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::paxos::Ack, ::paxos::CommitEntry, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Commit_, context, request);
}

::grpc::ClientAsyncResponseReader< ::paxos::Ack>* Paxos::Stub::AsyncCommitRaw(::grpc::ClientContext* context, const ::paxos::CommitEntry& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCommitRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Paxos::Stub::SendClientRequest(::grpc::ClientContext* context, const ::paxos::ClientRequest& request, ::paxos::TransactionAck* response) {
  return ::grpc::internal::BlockingUnaryCall< ::paxos::ClientRequest, ::paxos::TransactionAck, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendClientRequest_, context, request, response);
}

void Paxos::Stub::async::SendClientRequest(::grpc::ClientContext* context, const ::paxos::ClientRequest* request, ::paxos::TransactionAck* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::paxos::ClientRequest, ::paxos::TransactionAck, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendClientRequest_, context, request, response, std::move(f));
}

void Paxos::Stub::async::SendClientRequest(::grpc::ClientContext* context, const ::paxos::ClientRequest* request, ::paxos::TransactionAck* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendClientRequest_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::paxos::TransactionAck>* Paxos::Stub::PrepareAsyncSendClientRequestRaw(::grpc::ClientContext* context, const ::paxos::ClientRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::paxos::TransactionAck, ::paxos::ClientRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendClientRequest_, context, request);
}

::grpc::ClientAsyncResponseReader< ::paxos::TransactionAck>* Paxos::Stub::AsyncSendClientRequestRaw(::grpc::ClientContext* context, const ::paxos::ClientRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendClientRequestRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Paxos::Stub::NewView(::grpc::ClientContext* context, const ::paxos::NewViewRequest& request, ::paxos::Ack* response) {
  return ::grpc::internal::BlockingUnaryCall< ::paxos::NewViewRequest, ::paxos::Ack, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_NewView_, context, request, response);
}

void Paxos::Stub::async::NewView(::grpc::ClientContext* context, const ::paxos::NewViewRequest* request, ::paxos::Ack* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::paxos::NewViewRequest, ::paxos::Ack, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NewView_, context, request, response, std::move(f));
}

void Paxos::Stub::async::NewView(::grpc::ClientContext* context, const ::paxos::NewViewRequest* request, ::paxos::Ack* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NewView_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::paxos::Ack>* Paxos::Stub::PrepareAsyncNewViewRaw(::grpc::ClientContext* context, const ::paxos::NewViewRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::paxos::Ack, ::paxos::NewViewRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_NewView_, context, request);
}

::grpc::ClientAsyncResponseReader< ::paxos::Ack>* Paxos::Stub::AsyncNewViewRaw(::grpc::ClientContext* context, const ::paxos::NewViewRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncNewViewRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Paxos::Stub::ReceiveAcceptAck(::grpc::ClientContext* context, const ::paxos::Ack& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::paxos::Ack, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReceiveAcceptAck_, context, request, response);
}

void Paxos::Stub::async::ReceiveAcceptAck(::grpc::ClientContext* context, const ::paxos::Ack* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::paxos::Ack, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReceiveAcceptAck_, context, request, response, std::move(f));
}

void Paxos::Stub::async::ReceiveAcceptAck(::grpc::ClientContext* context, const ::paxos::Ack* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReceiveAcceptAck_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* Paxos::Stub::PrepareAsyncReceiveAcceptAckRaw(::grpc::ClientContext* context, const ::paxos::Ack& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::paxos::Ack, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReceiveAcceptAck_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* Paxos::Stub::AsyncReceiveAcceptAckRaw(::grpc::ClientContext* context, const ::paxos::Ack& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReceiveAcceptAckRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Paxos::Stub::SendAliveUpdate(::grpc::ClientContext* context, const ::paxos::AliveUpdateRequest& request, ::paxos::TransactionAck* response) {
  return ::grpc::internal::BlockingUnaryCall< ::paxos::AliveUpdateRequest, ::paxos::TransactionAck, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendAliveUpdate_, context, request, response);
}

void Paxos::Stub::async::SendAliveUpdate(::grpc::ClientContext* context, const ::paxos::AliveUpdateRequest* request, ::paxos::TransactionAck* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::paxos::AliveUpdateRequest, ::paxos::TransactionAck, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendAliveUpdate_, context, request, response, std::move(f));
}

void Paxos::Stub::async::SendAliveUpdate(::grpc::ClientContext* context, const ::paxos::AliveUpdateRequest* request, ::paxos::TransactionAck* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendAliveUpdate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::paxos::TransactionAck>* Paxos::Stub::PrepareAsyncSendAliveUpdateRaw(::grpc::ClientContext* context, const ::paxos::AliveUpdateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::paxos::TransactionAck, ::paxos::AliveUpdateRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendAliveUpdate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::paxos::TransactionAck>* Paxos::Stub::AsyncSendAliveUpdateRaw(::grpc::ClientContext* context, const ::paxos::AliveUpdateRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendAliveUpdateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Paxos::Stub::GetNodeInfo(::grpc::ClientContext* context, const ::paxos::InfoRequest& request, ::paxos::NodeInfo* response) {
  return ::grpc::internal::BlockingUnaryCall< ::paxos::InfoRequest, ::paxos::NodeInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetNodeInfo_, context, request, response);
}

void Paxos::Stub::async::GetNodeInfo(::grpc::ClientContext* context, const ::paxos::InfoRequest* request, ::paxos::NodeInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::paxos::InfoRequest, ::paxos::NodeInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetNodeInfo_, context, request, response, std::move(f));
}

void Paxos::Stub::async::GetNodeInfo(::grpc::ClientContext* context, const ::paxos::InfoRequest* request, ::paxos::NodeInfo* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetNodeInfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::paxos::NodeInfo>* Paxos::Stub::PrepareAsyncGetNodeInfoRaw(::grpc::ClientContext* context, const ::paxos::InfoRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::paxos::NodeInfo, ::paxos::InfoRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetNodeInfo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::paxos::NodeInfo>* Paxos::Stub::AsyncGetNodeInfoRaw(::grpc::ClientContext* context, const ::paxos::InfoRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetNodeInfoRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Paxos::Stub::SendMoveOn(::grpc::ClientContext* context, const ::paxos::MoveOnRequest& request, ::paxos::TransactionAck* response) {
  return ::grpc::internal::BlockingUnaryCall< ::paxos::MoveOnRequest, ::paxos::TransactionAck, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendMoveOn_, context, request, response);
}

void Paxos::Stub::async::SendMoveOn(::grpc::ClientContext* context, const ::paxos::MoveOnRequest* request, ::paxos::TransactionAck* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::paxos::MoveOnRequest, ::paxos::TransactionAck, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendMoveOn_, context, request, response, std::move(f));
}

void Paxos::Stub::async::SendMoveOn(::grpc::ClientContext* context, const ::paxos::MoveOnRequest* request, ::paxos::TransactionAck* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendMoveOn_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::paxos::TransactionAck>* Paxos::Stub::PrepareAsyncSendMoveOnRaw(::grpc::ClientContext* context, const ::paxos::MoveOnRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::paxos::TransactionAck, ::paxos::MoveOnRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendMoveOn_, context, request);
}

::grpc::ClientAsyncResponseReader< ::paxos::TransactionAck>* Paxos::Stub::AsyncSendMoveOnRaw(::grpc::ClientContext* context, const ::paxos::MoveOnRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendMoveOnRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Paxos::Stub::SendTwoPCMsg(::grpc::ClientContext* context, const ::paxos::TwoPCMsg& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::paxos::TwoPCMsg, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendTwoPCMsg_, context, request, response);
}

void Paxos::Stub::async::SendTwoPCMsg(::grpc::ClientContext* context, const ::paxos::TwoPCMsg* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::paxos::TwoPCMsg, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendTwoPCMsg_, context, request, response, std::move(f));
}

void Paxos::Stub::async::SendTwoPCMsg(::grpc::ClientContext* context, const ::paxos::TwoPCMsg* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendTwoPCMsg_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* Paxos::Stub::PrepareAsyncSendTwoPCMsgRaw(::grpc::ClientContext* context, const ::paxos::TwoPCMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::paxos::TwoPCMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendTwoPCMsg_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* Paxos::Stub::AsyncSendTwoPCMsgRaw(::grpc::ClientContext* context, const ::paxos::TwoPCMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendTwoPCMsgRaw(context, request, cq);
  result->StartCall();
  return result;
}

Paxos::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Paxos_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Paxos::Service, ::paxos::PrepareRequest, ::paxos::PromiseResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Paxos::Service* service,
             ::grpc::ServerContext* ctx,
             const ::paxos::PrepareRequest* req,
             ::paxos::PromiseResponse* resp) {
               return service->Prepare(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Paxos_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Paxos::Service, ::paxos::AcceptedEntry, ::paxos::Ack, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Paxos::Service* service,
             ::grpc::ServerContext* ctx,
             const ::paxos::AcceptedEntry* req,
             ::paxos::Ack* resp) {
               return service->Accept(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Paxos_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Paxos::Service, ::paxos::CommitEntry, ::paxos::Ack, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Paxos::Service* service,
             ::grpc::ServerContext* ctx,
             const ::paxos::CommitEntry* req,
             ::paxos::Ack* resp) {
               return service->Commit(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Paxos_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Paxos::Service, ::paxos::ClientRequest, ::paxos::TransactionAck, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Paxos::Service* service,
             ::grpc::ServerContext* ctx,
             const ::paxos::ClientRequest* req,
             ::paxos::TransactionAck* resp) {
               return service->SendClientRequest(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Paxos_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Paxos::Service, ::paxos::NewViewRequest, ::paxos::Ack, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Paxos::Service* service,
             ::grpc::ServerContext* ctx,
             const ::paxos::NewViewRequest* req,
             ::paxos::Ack* resp) {
               return service->NewView(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Paxos_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Paxos::Service, ::paxos::Ack, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Paxos::Service* service,
             ::grpc::ServerContext* ctx,
             const ::paxos::Ack* req,
             ::google::protobuf::Empty* resp) {
               return service->ReceiveAcceptAck(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Paxos_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Paxos::Service, ::paxos::AliveUpdateRequest, ::paxos::TransactionAck, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Paxos::Service* service,
             ::grpc::ServerContext* ctx,
             const ::paxos::AliveUpdateRequest* req,
             ::paxos::TransactionAck* resp) {
               return service->SendAliveUpdate(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Paxos_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Paxos::Service, ::paxos::InfoRequest, ::paxos::NodeInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Paxos::Service* service,
             ::grpc::ServerContext* ctx,
             const ::paxos::InfoRequest* req,
             ::paxos::NodeInfo* resp) {
               return service->GetNodeInfo(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Paxos_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Paxos::Service, ::paxos::MoveOnRequest, ::paxos::TransactionAck, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Paxos::Service* service,
             ::grpc::ServerContext* ctx,
             const ::paxos::MoveOnRequest* req,
             ::paxos::TransactionAck* resp) {
               return service->SendMoveOn(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Paxos_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Paxos::Service, ::paxos::TwoPCMsg, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Paxos::Service* service,
             ::grpc::ServerContext* ctx,
             const ::paxos::TwoPCMsg* req,
             ::google::protobuf::Empty* resp) {
               return service->SendTwoPCMsg(ctx, req, resp);
             }, this)));
}

Paxos::Service::~Service() {
}

::grpc::Status Paxos::Service::Prepare(::grpc::ServerContext* context, const ::paxos::PrepareRequest* request, ::paxos::PromiseResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Paxos::Service::Accept(::grpc::ServerContext* context, const ::paxos::AcceptedEntry* request, ::paxos::Ack* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Paxos::Service::Commit(::grpc::ServerContext* context, const ::paxos::CommitEntry* request, ::paxos::Ack* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Paxos::Service::SendClientRequest(::grpc::ServerContext* context, const ::paxos::ClientRequest* request, ::paxos::TransactionAck* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Paxos::Service::NewView(::grpc::ServerContext* context, const ::paxos::NewViewRequest* request, ::paxos::Ack* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Paxos::Service::ReceiveAcceptAck(::grpc::ServerContext* context, const ::paxos::Ack* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Paxos::Service::SendAliveUpdate(::grpc::ServerContext* context, const ::paxos::AliveUpdateRequest* request, ::paxos::TransactionAck* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Paxos::Service::GetNodeInfo(::grpc::ServerContext* context, const ::paxos::InfoRequest* request, ::paxos::NodeInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Paxos::Service::SendMoveOn(::grpc::ServerContext* context, const ::paxos::MoveOnRequest* request, ::paxos::TransactionAck* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Paxos::Service::SendTwoPCMsg(::grpc::ServerContext* context, const ::paxos::TwoPCMsg* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace paxos
#include <grpcpp/ports_undef.inc>

